### ISSUE TITLE
Warnings with ITK v5.1 + clang 11

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITKBSplineGradient#13]
[464/3196] Building CXX object Modules/Remote/BSplineGradient/test/CMak.../BSplineGradientTestDriver.dir/itkImageToImageOfVectorsFilterTest.cxx.o
In file included from /user/iibi/johnsonhj/src/ITK/Modules/Remote/BSplineGradient/test/itkImageToImageOfVectorsFilterTest.cxx:21:
/user/iibi/johnsonhj/src/ITK/Modules/Remote/BSplineGradient/include/itkImageToImageOfVectorsFilter.h:81:3: warning: 'itk::ImageToImageOfVectorsFilter<itk::Image<float, 2>, 2>::SetNthInput' hides overloaded virtual function [-Woverloaded-virtual]
  SetNthInput(DataObjectPointerArraySizeType idx, const InputImageType * inputImage)
  ^
/user/iibi/johnsonhj/src/ITK/Modules/Remote/BSplineGradient/test/itkImageToImageOfVectorsFilterTest.cxx:43:3: note: in instantiation of template class 'itk::ImageToImageOfVectorsFilter<itk::Image<float, 2>, 2>' requested here
  FilterType::Pointer filter = FilterType::New();
  ^
/user/iibi/johnsonhj/src/ITK/Modules/Core/Common/include/itkProcessObject.h:564:3: note: hidden overloaded virtual function 'itk::ProcessObject::SetNthInput' declared here: type mismatch at 2nd parameter ('itk::DataObject *' vs 'const itk::ImageToImageOfVectorsFilter<itk::Image<float, 2>, 2>::InputImageType *' (aka 'const itk::Image<float, 2> *'))
  SetNthInput(DataObjectPointerArraySizeType num, DataObject * input);
  ^
1 warning generated.
[629/3196] Building CXX object Modules/Remote/BSplineGradient/test/CMak...iver.dir/itkBSplineScatteredDataPointSetToGradientImageFilterTest.cxx.o
In file included from /user/iibi/johnsonhj/src/ITK/Modules/Remote/BSplineGradient/test/itkBSplineScatteredDataPointSetToGradientImageFilterTest.cxx:25:
/user/iibi/johnsonhj/src/ITK/Modules/Remote/BSplineGradient/include/itkImageToImageOfVectorsFilter.h:81:3: warning: 'itk::ImageToImageOfVectorsFilter<itk::Image<float, 2>, 1>::SetNthInput' hides overloaded virtual function [-Woverloaded-virtual]
  SetNthInput(DataObjectPointerArraySizeType idx, const InputImageType * inputImage)
  ^
/user/iibi/johnsonhj/src/ITK/Modules/Remote/BSplineGradient/test/itkBSplineScatteredDataPointSetToGradientImageFilterTest.cxx:47:3: note: in instantiation of template class 'itk::ImageToImageOfVectorsFilter<itk::Image<float, 2>, 1>' requested here
  ImageToVectorImageFilterType::Pointer imageToVI = ImageToVectorImageFilterType::New();
  ^
/user/iibi/johnsonhj/src/ITK/Modules/Core/Common/include/itkProcessObject.h:564:3: note: hidden overloaded virtual function 'itk::ProcessObject::SetNthInput' declared here: type mismatch at 2nd parameter ('itk::DataObject *' vs 'const itk::ImageToImageOfVectorsFilter<itk::Image<float, 2>, 1>::InputImageType *' (aka 'const itk::Image<float, 2> *'))
  SetNthInput(DataObjectPointerArraySizeType num, DataObject * input);
  ^
1 warning generated.
[654/3196] Building CXX object Modules/Remote/BSplineGradient/test/CMak...ientTestDriver.dir/itkBSplineApproximationGradientImageFilterTest.cxx.o
In file included from /user/iibi/johnsonhj/src/ITK/Modules/Remote/BSplineGradient/test/itkBSplineApproximationGradientImageFilterTest.cxx:23:
/user/iibi/johnsonhj/src/ITK/Modules/Remote/BSplineGradient/include/itkImageToImageOfVectorsFilter.h:81:3: warning: 'itk::ImageToImageOfVectorsFilter<itk::Image<float, 2>, 1>::SetNthInput' hides overloaded virtual function [-Woverloaded-virtual]
  SetNthInput(DataObjectPointerArraySizeType idx, const InputImageType * inputImage)
  ^
/user/iibi/johnsonhj/src/ITK/Modules/Remote/BSplineGradient/test/itkBSplineApproximationGradientImageFilterTest.cxx:46:3: note: in instantiation of template class 'itk::ImageToImageOfVectorsFilter<itk::Image<float, 2>, 1>' requested here
  ImageToVectorImageFilterType::Pointer imageToVI = ImageToVectorImageFilterType::New();
  ^
/user/iibi/johnsonhj/src/ITK/Modules/Core/Common/include/itkProcessObject.h:564:3: note: hidden overloaded virtual function 'itk::ProcessObject::SetNthInput' declared here: type mismatch at 2nd parameter ('itk::DataObject *' vs 'const itk::ImageToImageOfVectorsFilter<itk::Image<float, 2>, 1>::InputImageType *' (aka 'const itk::Image<float, 2> *'))
  SetNthInput(DataObjectPointerArraySizeType num, DataObject * input);
  ^
1 warning generated.

**Comment by hjmjohnson** [comment]
@mseng10 Please address when you are working on remote modules.

**Comment by mseng10** [comment]
@hjmjohnson I will address this now.

**Comment by dzenanz** [comment]
Please reopen if the issue was not fixed.
